steps:
- name: 'gcr.io/cloud-builders/mvn'
  args: ['package']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/slide4vr-backend', '-f', 'src/main/docker/Dockerfile.jvm', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/slide4vr-backend']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', 'slide4vr-backend', 
  '--image', 'gcr.io/$PROJECT_ID/slide4vr-backend', 
  '--region', 'us-central1', 
  '--platform', 'managed', 
  '--service-account', 'slide2vr-api@slide2vr.iam.gserviceaccount.com'
  ]
images:
- gcr.io/$PROJECT_ID/slide4vr-backend